spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        # =====================================
        # 服务提供者服务路由规则
        - id: provider_route
          uri: lb://provider
          predicates:
            - Path=/provider/**
        # =====================================
        # 服务提供者服务路由规则
        - id: customer_route
          uri: lb://customer
          predicates:
            - Path=/customer/**