server:
  port: 80

spring:
  application:
    name: gateway
  profiles:
    active: route

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka